feat: add video loader
jina-ai/executors pull request #257
Opened 2021-10-01 15:44 UTC by makram93

Video Loader that loads frames and audio as chunks which can be retrieved by using `modality='audio' or modality='image'`.

2021-10-01 16:57 UTC, tadejsv commented
Two comments:
- if you want to create temporary files/directories, use python's `tempfile` library
- you might not even need that. You can use ffmpeg to read the video directly to frames, see https://github.com/kkroening/ffmpeg-python/blob/master/examples/README.md#convert-video-to-numpy-array . For audio it might be a bit harder, but I think still possible?

2021-10-04 06:37 UTC, nan-wang requested changes

2021-10-04 06:37 UTC, nan-wang commented on jinahub/loaders/VideoLoader/README.md
> +- To override class metas, use `.add(..., uses_metas: {'key': 'value})`
delete. Check out https://docs.google.com/document/d/1UebHh5WDArscXZkT5TKENDdsce0n9KmvkHJkoucBT_w/edit

2021-10-04 11:07 UTC, CatStark requested changes
Can you move this outside from this repo please? It should be on its own repo

2021-10-07 07:47 UTC, closed without merging