refactor: train and index
jina-ai/executors pull request #284
Opened 2021-10-26 11:17 UTC by numb3r3

2021-11-03 10:29 UTC, cristianmtr requested changes

2021-11-03 10:29 UTC, cristianmtr commented on jinahub/indexers/searcher/FaissSearcher/tests/integration/test_train_index.py
> +        # train and index docs first
Didn't we say that we want the trained index to contain the data as well?

so just

- train outside 
- start Flow -- Faiss gets pretrained model with data
- search on the data is ready

2021-11-04 11:09 UTC, tadejsv approved these changes
Looks good to me

2021-11-05 07:51 UTC, cristianmtr approved these changes

2021-11-05 08:03 UTC, merged