fix: raise error in `DPRTextEncoder` when context encoder has incorrect model and update readme
jina-ai/executors pull request #308
Opened 2021-12-10 03:48 UTC by winstonww

Goals:

- [x] As per https://github.com/jina-ai/executors/issues/305, `DPRTextEncoder` is unable to start for context encoder if model path is not correctly set. The PR updates the README and raise meaningful exceptions when this happens

- [ ] Bumped version (in README of Executor)

PR feedback: @jina-ai/workstream-hub

2021-12-10 12:37 UTC, cristianmtr requested changes

2021-12-10 12:37 UTC, cristianmtr commented on jinahub/encoders/text/DPRTextEncoder/dpr_text.py
> +                'to a dpr context encoder model.'
```suggestion
                'to a dpr context encoder model. e.g. "facebook/dpr-ctx_encoder-single-nq-base" '
```

2021-12-13 08:31 UTC, winstonww commented on jinahub/encoders/text/DPRTextEncoder/dpr_text.py
> +                'to a dpr context encoder model.'
Thanks, addressed [here](https://github.com/jina-ai/executors/pull/308/commits/2bde1f6eed4c338b71bc3b7ad3ca8e5915f84a3b).

2021-12-13 09:15 UTC, cristianmtr approved these changes

2021-12-13 15:32 UTC, nan-wang approved these changes
LGTM👍

2021-12-13 15:32 UTC, merged