fix(audio-clip-encoder): remove .eval which mess with the model outputs
jina-ai/executors pull request #315
Opened 2022-01-21 10:08 UTC by samsja

Goals:

- ...
- ...

- [ ] Bumped version (in README of Executor)

PR feedback: @jina-ai/workstream-hub

2022-01-21 10:53 UTC, cristianmtr requested changes

2022-01-21 10:53 UTC, cristianmtr commented on jinahub/encoders/audio/AudioCLIPEncoder/executor/audio_clip_encoder.py
> +            #self.model = AudioCLIP(pretrained=self.model_path).to(self.device).eval()
remove comment line?

2022-01-21 11:02 UTC, samsja commented on jinahub/encoders/audio/AudioCLIPEncoder/executor/audio_clip_encoder.py
> +            #self.model = AudioCLIP(pretrained=self.model_path).to(self.device).eval()
Yes sure

2022-01-21 13:21 UTC, JoanFM requested changes
Block this PR. Because this does not make much sense.

Prediction should not be affected by batch normalization

2022-01-21 13:26 UTC, cristianmtr commented
> Block this PR. Because this does not make much sense.
> 
> Prediction should not be affected by batch normalization

We had the same problem in the fashion search workstream in the beginning. See [here](https://jinaai.slack.com/archives/C018QC78L84/p1635939926059900?thread_ts=1635885102.049600&cid=C018QC78L84). Is this related? When in evaluation (prediction without learning) mode you don't want BatchNorm, right?

2022-01-21 13:46 UTC, JoanFM commented
> > Block this PR. Because this does not make much sense.
> > Prediction should not be affected by batch normalization
> 
> We had the same problem in the fashion search workstream in the beginning. See [here](https://jinaai.slack.com/archives/C018QC78L84/p1635939926059900?thread_ts=1635885102.049600&cid=C018QC78L84). Is this related? When in evaluation (prediction without learning) mode you don't want BatchNorm, right?

Yes, the point here is we are suggesting that using eval is the source of the problem.

If that is true that the paper author does not use eval in their notebook, we should query on their github repo asking why.

After all at inference time inference in batch should give same vectors as doing it one by one

2022-01-21 14:06 UTC, JohannesMessner commented
> > > Block this PR. Because this does not make much sense.
> > > Prediction should not be affected by batch normalization
> > 
> > 
> > We had the same problem in the fashion search workstream in the beginning. See [here](https://jinaai.slack.com/archives/C018QC78L84/p1635939926059900?thread_ts=1635885102.049600&cid=C018QC78L84). Is this related? When in evaluation (prediction without learning) mode you don't want BatchNorm, right?
> 
> Yes, the point here is we are suggesting that using eval is the source of the problem.
> 
> If that is true that the paper author does not use eval in their notebook, we should query on their github repo asking why.
> 
> After all at inference time inference in batch should give same vectors as doing it one by one

We don't really understand what is going on in .eval(), but we don't think that it is just batch norm; it seems that calling it completely changes the behaviour of forward(). The author doesn't seem to implement eval() himself, so it probably has something to do with one of the models that are inside his model. We can ask him.
Btw, the implementation in general seems a bit dodgy, so we don't have a great feeling about it even if we fix this particular problem.

2022-01-22 10:31 UTC, JoanFM commented
> > > > Block this PR. Because this does not make much sense.
> > > > Prediction should not be affected by batch normalization
> > > 
> > > 
> > > We had the same problem in the fashion search workstream in the beginning. See [here](https://jinaai.slack.com/archives/C018QC78L84/p1635939926059900?thread_ts=1635885102.049600&cid=C018QC78L84). Is this related? When in evaluation (prediction without learning) mode you don't want BatchNorm, right?
> > 
> > 
> > Yes, the point here is we are suggesting that using eval is the source of the problem.
> > If that is true that the paper author does not use eval in their notebook, we should query on their github repo asking why.
> > After all at inference time inference in batch should give same vectors as doing it one by one
> 
> We don't really understand what is going on in .eval(), but we don't think that it is just batch norm; it seems that calling it completely changes the behaviour of forward(). The author doesn't seem to implement eval() himself, so it probably has something to do with one of the models that are inside his model. We can ask him. Btw, the implementation in general seems a bit dodgy, so we don't have a great feeling about it even if we fix this particular problem.

Have we tried to run his notebook where both the audio and the text embedding are done without batching, and with/without eval?

2022-01-24 14:48 UTC, nan-wang commented on jinahub/encoders/audio/AudioCLIPEncoder/executor/audio_clip_encoder.py
> +        ((embeddings, _, _), _), _ = self.model(audio=inputs)
Have we check out the functionality of `logits`? In the original demo, the author is using these `logits` for comparing similarities. https://github.com/AndreyGuzhov/AudioCLIP/blob/master/demo/AudioCLIP.ipynb

https://github.com/jina-ai/executors/blob/1825246962f557b2a2b8b8d513922c5c25fff007/jinahub/encoders/audio/AudioCLIPEncoder/executor/audio_clip/model/audioclip.py#L150-L175

2022-01-25 03:51 UTC, nan-wang commented
I would like to reject this PR because removing `.eval()` will leads to inconsistent embeddings. This is an upstream issue. Let's raise it up to the upstream author. Here is the code snippets from @winstonww  to show the bug.

```python
import torch
from model import AudioCLIP
aclp = AudioCLIP(pretrained=f'assets/AudioCLIP-Full-Training.pt')
a1 = torch.zeros((1000))
a2 = torch.rand((1000))
a3 = torch.rand((1000))

batch1 = torch.stack([a1, a2])
batch2 = torch.stack([a1, a3])

((batch1_output, _, _), _), _ = aclp(audio=batch1)
((batch2_output, _, _), _), _ = aclp(audio=batch2)
# a1's embedding should be the same regard less of batching
assert batch1_output[0].equal(batch2_output[0])
```

reference:
https://jinaai.slack.com/archives/C0183GCN8AK/p1643031021046800?thread_ts=1643019655.039700&cid=C0183GCN8AK

2022-01-25 03:51 UTC, closed without merging

2022-01-25 08:01 UTC, cristianmtr commented
Just FYI the author doesn't have Issues open in their repo.