Migrate drp text to jina3
jina-ai/executors pull request #317
Opened 2022-01-25 10:55 UTC by samsja

DO NOT MERGE before changing back the cicd to use the latest jina3 release instead of the master branch

2022-01-28 08:52 UTC, JoanFM requested changes

2022-01-28 08:52 UTC, JoanFM commented on jinahub/encoders/text/DPRTextEncoder/dpr_text.py
> +        traversal_paths: Iterable[str] = '@r',
the type hint seems wrong

2022-02-01 08:44 UTC, JoanFM approved these changes

2022-02-11 14:31 UTC, samsja commented
moved to https://github.com/jina-ai/executor-text-dpr-encoder

2022-02-11 14:31 UTC, closed without merging