feat: add huggingface clipimage transformers
jina-ai/executors pull request #45
Opened 2021-07-31 15:20 UTC by makram93

Hi @tadejsv,

I am raising the PR. Waiting for your feedback

2021-07-31 15:28 UTC, makram93 commented
I ran this test locally and it passed: CLIPImageEncoder/tests/unit/test_clip.py::test_openai_embed_match 
However, it is failing in CI check. Why is that happening?

2021-08-01 16:43 UTC, JoanFM submitted a review, later dismissed
Please keep `use_default_preprocessing` option for now

2021-08-01 16:43 UTC, JoanFM commented on jinahub/encoders/image/CLIPImageEncoder/clip_image.py
> +                    for idx, doc in enumerate(batch_docs):
u can use zip

2021-08-01 23:13 UTC, makram93 commented
@JoanFM, 
I have added the `use_default_preprocessing` param in my latest commit.

@tadejsv,
I have noticed that in hugginface implementation they perform `transforms.ToTensor()` after `center_crop` transformation. However, in your `AudioCLIPImageEncoder`, you have set 'ToTensor()' as first step in `_default_transform`. This does not impact the semantic test but the embedding values obtained are different. This happens because `ToTensor` scales the value between [0, 1] using the entire pixels whereas when used after `center_crop`, it only considers the cropped pixels for scaling. A small example below, in which if we perform `ToTensor` as the first operation then the embeddings don't match the original embeddings. 
``` python
    _IMAGE_SIZE = 224
    _IMAGE_MEAN = 0.48145466, 0.4578275, 0.40821073
    _IMAGE_STD = 0.26862954, 0.26130258, 0.27577711

    from PIL import Image
    import requests
    from transformers import CLIPProcessor, CLIPModel

    url = "http://images.cocodataset.org/val2017/000000039769.jpg"
    image = Image.open(requests.get(url, stream=True).raw)

    model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")

    # Using processor
    processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")
    inputs = processor(images=image, return_tensors="pt")
    outputs_p = model.get_image_features(**inputs).detach().cpu().numpy()

    # Using transforms with ToTensor after resize
    default_transforms = transforms.Compose(
        [
            transforms.ToPILImage(),
            transforms.Resize(_IMAGE_SIZE, interpolation=Image.BICUBIC),
            transforms.CenterCrop(_IMAGE_SIZE),
            transforms.ToTensor(),
            transforms.Normalize(_IMAGE_MEAN, _IMAGE_STD),
        ]
    )
    images = default_transforms(np.array(image)).unsqueeze(dim=0)
    outputs_t1 = model.get_image_features(images).detach().cpu().numpy()

    # Using transforms with ToTensor in the first step
    default_transforms = transforms.Compose(
        [
            transforms.ToTensor(),
            transforms.Resize(_IMAGE_SIZE, interpolation=Image.BICUBIC),
            transforms.CenterCrop(_IMAGE_SIZE),
            transforms.Normalize(_IMAGE_MEAN, _IMAGE_STD),
        ]
    )
    images = default_transforms(image).unsqueeze(dim=0)
    outputs_t2 = model.get_image_features(images).detach().cpu().numpy()

    np.testing.assert_almost_equal(outputs_p, outputs_t2, 5)
```

2021-08-02 15:52 UTC, tadejsv requested changes
As always, great job :)

I've left some comments - the main thing is to use CLIPFeatureExtractor for preprocessing.

Regarding your commend on order of transforms - where do you think this comes up?
The failure of the tests before was only for one image, so I don't think it was this. But in any case I will check this again after you apply the changes.

2021-08-02 15:52 UTC, tadejsv commented on jinahub/encoders/image/CLIPImageEncoder/README.md
> +- `device`: device that the model is on (should be "cpu", "cuda" or "cuda:X",
Also add back default preprocessing arg heere

2021-08-02 15:52 UTC, tadejsv commented on jinahub/encoders/image/CLIPImageEncoder/README.md
> +        volumes='/your_home_folder/.cache/clip:/root/.cache/clip')
This volume is not needed anymore

2021-08-02 15:52 UTC, tadejsv commented on jinahub/encoders/image/CLIPImageEncoder/README.md
> +    volumes: '/your_home_folder/.cache/clip:/root/.cache/clip'
Also not needed

2021-08-02 15:52 UTC, tadejsv commented on jinahub/encoders/image/CLIPImageEncoder/README.md
> +f = Flow().add(uses='jinahub://CLIPImageEncoder',
```suggestion
f = Flow().add(uses='jinahub://CLIPImageEncoder')

```

2021-08-02 15:52 UTC, tadejsv commented on jinahub/encoders/image/CLIPImageEncoder/README.md
> +- `use_default_preprocessing`: Whether to use the default preprocessing on
Also, can you add a parameter here `base_feature_extractor` - exactly the same logic as `base_tokenizer` in the text version

2021-08-02 16:02 UTC, tadejsv commented
One more comment here: from what I see HF will only divide by 255 and transform to float if the image is a PIL image, if it is a numpy image it will assume this is already the case. So you should also do that manually in case of default preprocessing.

And the `ToTensor` transform actually also does that (divide by 255), so this is the source of the differences in your example.

2021-08-03 08:28 UTC, makram93 commented
Hi @tadejsv ,

I checked the `__call__` method in `CLIPFeatureExtractor` . It performs [resize](https://huggingface.co/transformers/_modules/transformers/models/clip/feature_extraction_clip.html#CLIPFeatureExtractor.resize) and [center crop](https://huggingface.co/transformers/_modules/transformers/models/clip/feature_extraction_clip.html#CLIPFeatureExtractor.center_crop) on PIL Image only. If it is `nd.array` then it converts it to PIL Image. After that it performs [normalization](https://huggingface.co/transformers/_modules/transformers/image_utils.html#ImageFeatureExtractionMixin.normalize) during which it converts the PIL Image to a numpy array and divides it by 255. So I think we don't need to manually divide numpy image before feeding it to  `CLIPFeatureExtractor`

2021-08-03 08:30 UTC, tadejsv commented
@makram93 We need to do the division by 255, because our documents contain `blob`s - which are numpy arrays and not PIL images. Same reason for needing to switch the channel axis to the first place

2021-08-03 08:50 UTC, makram93 commented
@tadejsv I understand that we have numpy arrays in `blobs` but if we pass it through `CLIPFeatureExtractor` preprocessor then it will automatically handle it by first converting it to PIL and then later dividing it by 255 before normalising it.

I am little confused now. This is what I have understood so far. Correct me if I'm wrong. We keep two args `base_feature_extractor` and `use_default_preprocessing` in `clip_image.py`. 
- If `use_default_preprocessing=True`, then we accept arrays with uint or float as dtype. In this sceanrio we use `CLIPFeatureExtractor` to preprocess it. We don't need to shift axis as [`to_pil_image`](https://huggingface.co/transformers/_modules/transformers/image_utils.html#ImageFeatureExtractionMixin.to_pil_image) handles it. Neither we need to divide it by 255 as [`to_numpy_array`](https://huggingface.co/transformers/_modules/transformers/image_utils.html#ImageFeatureExtractionMixin.to_numpy_array) handles it
- If `use_default_preprocessing=False`, then we assume preprocessing has already been done and we simply create a tensor out of it and pass it to the model to get embeddings.

2021-08-03 08:55 UTC, tadejsv commented
> @tadejsv I understand that we have numpy arrays in `blobs` but if we pass it through `CLIPFeatureExtractor` preprocessor then it will automatically handle it by first converting it to PIL and then later dividing it by 255 before normalising it.

I see you are right, this happens in resize and center crop. Then good, we don't need to do it actually.

> I am little confused now. This is what I have understood so far. Correct me if I'm wrong. We keep two args `base_feature_extractor` and `use_default_preprocessing` in `clip_image.py`.
> 
> * If `use_default_preprocessing=True`, then we accept arrays with uint or float as dtype. In this sceanrio we use `CLIPFeatureExtractor` to preprocess it. We don't need to shift axis as [`to_pil_image`](https://huggingface.co/transformers/_modules/transformers/image_utils.html#ImageFeatureExtractionMixin.to_pil_image) handles it. Neither we need to divide it by 255 as [`to_numpy_array`](https://huggingface.co/transformers/_modules/transformers/image_utils.html#ImageFeatureExtractionMixin.to_numpy_array) handles it
> * If `use_default_preprocessing=False`, then we assume preprocessing has already been done and we simply create a tensor out of it and pass it to the model to get embeddings.

Yes, all correct

2021-08-03 15:46 UTC, makram93 commented
Hi @tadejsv,

I have pushed the code with updated changes.

2021-08-04 05:04 UTC, nan-wang commented
@makram93 I'm afraid the test is failing https://github.com/jina-ai/executors/pull/45/checks?check_run_id=3232579039#step:4:415

2021-08-04 08:03 UTC, tadejsv requested changes

2021-08-04 08:03 UTC, tadejsv commented on jinahub/encoders/image/CLIPImageEncoder/tests/unit/test_clip.py
> +    cat = Document(id="cat", blob=np.array(Image.open(data_dir / "cat.jpg")))
Just remove the cat. I did some exploring, and the difference is in how HF and CLIP (torchvision transforms) implement the resize + centercrop transformations. The difference is subtle - i saved both images with only these 2 transformations and they looked visually the same, yet their pixel values were different.

Not sure why exactly this is, but in any case there is nothing that can be done about this, nor do I think it should be a major problem.

2021-08-04 08:58 UTC, makram93 commented
@tadejsv done

2021-08-04 09:31 UTC, tadejsv approved these changes
@makram93 Good job!!

2021-08-04 12:33 UTC, tadejsv approved these changes
Some tidbits

2021-08-04 12:33 UTC, tadejsv commented on jinahub/encoders/image/CLIPImageEncoder/clip_image.py
> +        device: Optional[str] = "cpu",
```suggestion
        device: str = "cpu",
```

2021-08-04 12:45 UTC, tadejsv approved these changes
Ready to merge

2021-08-04 12:46 UTC, merged