fix: no logging of searching
jina-ai/executors pull request #99
Opened 2021-08-17 08:17 UTC by cristianmtr

2021-08-17 13:17 UTC, numb3r3 approved these changes
LGTM

2021-08-19 15:05 UTC, maximilianwerk requested changes
to cleanup otherwise LGTM

2021-08-19 15:05 UTC, maximilianwerk commented on jinahub/indexers/storage/PostgreSQLStorage/postgreshandler.py
> +            print(f'### NO METAS', flush=True)
remove that print?

2021-08-19 15:05 UTC, maximilianwerk commented on tests/requirements.txt
> +jina_commons @ git+https://github.com/jina-ai/jina-commons@feat-optional-metas
revert to main

2021-08-20 02:18 UTC, numb3r3 requested changes

2021-08-20 02:18 UTC, numb3r3 commented on jinahub/indexers/storage/PostgreSQLStorage/postgreshandler.py
> +                    );'
This is a breaking change. Could we also release a tag-specific one without changing the table columns?  As, our EAP custom already has millions of docs stored n PostgresStorage.

2021-08-20 06:59 UTC, numb3r3 commented on jinahub/indexers/storage/PostgreSQLStorage/postgreshandler.py
> +                    );'
I just got some feedbacks from our eap partner, they said they can re-index their data. So I think we are free to release the new psql indexer

2021-08-20 07:00 UTC, numb3r3 approved these changes
LGTM

2021-08-20 07:16 UTC, merged